modulelist=com.p6spy.engine.spy.P6SpyFactory,com.p6spy.engine.logging.P6LogFactory
driverlist=org.postgresql.Driver
appender=com.p6spy.engine.spy.appender.FileLogger
logfile=/app/logs/sql.log
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)
excludecategories=info,debug,result,resultset
append=false
